#!/bin/sh

if ! test -d .git; then
    echo "Execute scripts/install-git-hooks in the top-level directory."
    exit 1
fi

HOOKS=scripts

installed=0
for hook in "$HOOKS"/*.hook; do
    [ -f "$hook" ] || break
    name=$(basename "$hook" .hook)
    ln -sf "../../$hook" ".git/hooks/$name" || exit 1
    chmod +x ".git/hooks/$name" || exit 1
    installed=1
done

if [ "$installed" -eq 0 ]; then
    echo "[!] No hooks found in $HOOKS" >&2
    exit 1
fi

touch .git/hooks/applied || exit 1

echo
echo "Git hooks are installed successfully."
